services:
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    container_name: sqlserver_container
    restart: always
    environment:
      - 'ACCEPT_EULA=yes'
      - 'MSSQL_PID=Standard'
      - 'MSSQL_SA_PASSWORD=${DB_PASSWORD}'
    volumes:
      - sqlserver_data:/var/opt/mssql/
    ports:
      - '1433:1433'
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${DB_PASSWORD} -C -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    networks:
      - orders_network

  localstack:
    image: localstack/localstack
    container_name: localstack_container
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,sqs,lambda,ses,iam,sts
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/tmp/localstack:/tmp/localstack/state"
    networks:
      - orders_network

volumes:
  sqlserver_data:
    driver: local

networks:
  orders_network:
    name: orders_network
    driver: bridge